name: Metrics

on:
  # Update metrics once every day at midnight
  schedule:
    - cron: "0 0 * * *"

  # Allow manual runs from GitHub Actions
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Account
          user: dev-syedghani

          # Template
          template: classic

          # Base sections
          base: header, activity, community, repositories, metadata

          # Timezone
          config_timezone: Asia/Karachi

          # Follow-up plugin
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          # Lines of code plugin
          plugin_lines: yes
          plugin_lines_sections: repositories

          # Stargazers plugin
          plugin_stargazers: yes
